openapi: 3.0.0
info:
  title: Fusorario-Api
  description: Documentazione OpenAPI sul servizio di fuso orario.
  contact:
    email: d.nicolosi@campus.uniurb.it
  license:
    name: MIT
    url: https://mit-license.org/
  version: 1.0.1
servers:
- url: https://api-fusorario.herokuapp.com/
  description: Main server
tags:
- name: Fuso orario
  description: Servizio di ora e data sulle diverse zone di fuso orario.
paths:
  /ip:
    get:
      tags:
      - Indirizzo ip
      summary: Geolocalizzazione per inidirizzo ip
      description: Dato un indirizzo ip, viene geocalizzato e ne viene dato il fuso
        orario. In caso non sia specificato un indirizzo ip, viene utilizzato l'indirizzo
        del client che effettua la richiesta.
      parameters:
      - name: ip
        in: query
        description: indirizzo ip di cui si vuole conoscere il fuso orario.
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      responses:
        200:
          description: Risposta OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IpTimezone'
        400:
          description: Richiesta errata
        401:
          description: Autenticazione fallita
        503:
          description: Servizio non disponibile
    post:
      tags:
      - Indirizzo ip
      summary: Geolocalizzazione per inidirizzo ip
      description: Dato un indirizzo ip, viene geocalizzato e ne viene dato il fuso
        orario. In caso non sia specificato un indirizzo ip, viene utilizzato l'indirizzo
        del client che effettua la richiesta.
      parameters:
      - name: ip
        in: query
        description: indirizzo ip di cui si vuole conoscere il fuso orario.
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      responses:
        200:
          description: Risposta OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IpTimezone'
        400:
          description: Richiesta errata
        401:
          description: Autenticazione fallita
        503:
          description: Servizio non disponibile
  /timezone:
    get:
      tags:
      - Zona
      summary: Fuso orario da zona
      description: Data una zona formata da {area}/{localita} viene dato il fuso orario.
        Se non viene specificata una zona, viene stampata la lista delle zone.
      parameters:
      - name: timezone
        in: query
        description: zona di cui si vuole conoscere il fuso orario.
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      responses:
        200:
          description: Risposta OK
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ZoneTimezone'
                - $ref: '#/components/schemas/ListTimezone'
        400:
          description: Richiesta errata
        401:
          description: Autenticazione fallita
        503:
          description: Servizio non disponibile
    post:
      tags:
      - Zona
      summary: Fuso orario da zona
      description: Data una zona formata da {area}/{localita} viene dato il fuso orario.
        Se non viene specificata una zona, viene stampata la lista delle zone.
      parameters:
      - name: timezone
        in: query
        description: zona di cui si vuole conoscere il fuso orario.
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: string
      responses:
        200:
          description: Risposta OK
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ZoneTimezone'
                - $ref: '#/components/schemas/ListTimezone'
        400:
          description: Richiesta errata
        401:
          description: Autenticazione fallita
        503:
          description: Servizio non disponibile
components:
  schemas:
    ListTimezone:
      type: array
      description: Lista delle zone di fuso orario disponibili
      items:
        type: string
    IpTimezone:
      properties:
        ip:
          type: string
          description: Indirizzo ip richiesto
        week_number:
          type: integer
          description: Numero della settimana dell'anno
        day_of_year:
          type: integer
          description: Numero del giorno dell'anno
        day_of_week:
          type: integer
          description: Numero del giorno della settimana
        utc_offset:
          type: string
          description: Scostamento dal formato UTC
        date:
          type: string
          description: Data
        time:
          type: string
          description: Orario
        timezone:
          type: string
          description: Zona di fuso orario
    ZoneTimezone:
      properties:
        week_number:
          type: integer
          description: Numero della settimana dell'anno
        day_of_year:
          type: integer
          description: Numero del giorno dell'anno
        day_of_week:
          type: integer
          description: Numero del giorno della settimana
        utc_offset:
          type: string
          description: Scostamento dal formato UTC
        date:
          type: string
          description: Data
        time:
          type: string
          description: Orario
        timezone:
          type: string
          description: Zona di fuso orario
    Error:
      type: string
      description: Errore nell'interrogazione dell'api
  responses:
    JsonListTimezone:
      description: 'Lista delle zone di fuso orario in formato JSON '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListTimezone'
    JsonIpTimezone:
      description: Fuso orario della geolocalizzazione dell'ip in formato JSON
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IpTimezone'
    JsonZoneTimezone:
      description: Fuso orario della zona in formato JSON
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ZoneTimezone'
    Error:
      description: Fuso orario della geolocalizzazione dell'ip in formato JSON
      content:
        text/plain:
          schema:
            $ref: '#/components/schemas/Error'
